include:
  - board: seeeduino_xiao_rp2040
    shield: totem_left
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_rp2040
    shield: totem_right
    snippet: zmk-usb-logging
# there is no settingsreset (needed) for the XIAO
